### ISSUE TITLE
can build roads anywhere

### ISSUE THREAD

**Issue by tallbird** [PaulTorry/HexGame#25]
expected behaviour - need to research nav beacon technology to build roads. can only build a road if ship is in that hex
current behaviour - can build roads anywhere regardless of technology research or whether ships are in hex or not

**Comment by tallbird** [comment]
can also build asteroid mining without tech, and all ship types without appropriate tech, so a tech tree problem?

**Comment by tallbird** [comment]
just tested gas giant movement and that one works as expected

**Comment by PaulTorry** [comment]
Spreadsheet updated and variables changed.
